### ISSUE TITLE
xhyverun-tinycorelinux.sh and xhyve-windows.sh attempt to execute xhyve relative to build/Release/ rather than build/.

### ISSUE THREAD

**Issue by OliverFrancis** [machyve/xhyve#155]
Reproduction Steps:

1) make

2) ./xhyverun-tinycorelinux.sh 
./xhyverun-tinycorelinux.sh: line 4: build/Release/xhyve: No such file or directory

OR

1) make
2) ./xhyverun-windows.sh 
./xhyverun-windows.sh: line 8: build/Release/xhyve: No such file or directory

**Comment by gpolitis** [comment]
The README recommends using xcodebuild, which puts the binary in build/Release/xhyve. I wonder if it would make sense to modify the Makefile to put the binary in the same place as the xcodebuild tool.

**Comment by jeremyhu** [comment]
The Makefile exists mainly for folks cross-compiling on other platforms, so I don't think we need to change much there (and touching it might disturb those configurations as well).  I think PR #156 addressed this ok.  If it turns out folks were dependent on the paths that the Makefile produced, we should just update the scripts to use `xhyve` (ie: search $PATH for the installed executable)
